### ISSUE TITLE
Erro Checkout Magento 2.1.6

### ISSUE THREAD

**Issue by gustavo-campos** [setor7soft/magento2-cielo#1]
Uso o Magento 2.1.6 
No Checkout não finaliza a compra 
segue abaixo do o erro
jquery.js:9666 POST /rest/default/V1/carts/mine/payment-information 400 (Bad Request)
send	@	jquery.js:9666
ajax	@	jquery.js:9211
post	@	storage.js:39
(anonymous)	@	place-order.js:17
(anonymous)	@	place-order.js:33
_super	@	wrapper.js:73
(anonymous)	@	place-order-mixin.js:20
(anonymous)	@	wrapper.js:78
getPlaceOrderDeferredObject	@	default.js:163
placeOrder	@	cielo.js:410
(anonymous)	@	knockout.js:3863
dispatch	@	jquery.js:4624
elemData.handle	@	jquery.js:4292
﻿

​

**Comment by lukasfeliphe** [comment]
Gustavo conseguiu resolver ? também estou com esse problema

**Comment by Rhodion** [comment]
Estou com o mesmo problema. 

Response da página é esse:

{"message":"An error occurred on the server. Please try to place the order again.","trace":"#0 \/var\/www\/html\/pec\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): Magento\\Checkout\\Model\\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(56, Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#1 \/var\/www\/html\/pec\/var\/generation\/Magento\/Checkout\/Model\/PaymentInformationManagement\/Interceptor.php(26): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)\n#2 [internal function]: Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder(56, Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#3 \/var\/www\/html\/pec\/vendor\/magento\/module-webapi\/Controller\/Rest.php(307): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/pec\/vendor\/magento\/module-webapi\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#5 \/var\/www\/html\/pec\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/var\/www\/html\/pec\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/var\/www\/html\/pec\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#8 \/var\/www\/html\/pec\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#9 {main}"}

**Comment by Rhodion** [comment]
Bom dia pessoal. 
O erro é o cartão do sandbox.
Testamos com esses dados e funcionou.

 "CreditCard":{  
         "CardNumber":"4024007197692931",
         "Holder":"Teste Holder",
         "ExpirationDate":"12/2021",
         "SecurityCode":"123",
         "SaveCard":"false",
         "Brand":"Visa"
     }

**Comment by marcelowu** [comment]
acho q problema esta aqui
    const ENVIRONMENT_PRODUCTION = 'sandbox';
    const ENVIRONMENT_SANDBOX = 'production';
para teste em vez de sandbox vc coloca production.
